// Canonical GHS/CLP hazard (H) and precautionary (P) statement text.
// Source: UN GHS Rev. 9 and EU CLP Regulation Annex III/IV (Spanish).
// Combined codes (e.g. "H301+H311+H331") are resolved at render time from the
// individual statements. Only single-code entries live here.

export const H_STATEMENTS: Record<string, string> = {
  // Peligros físicos (H200-H290)
  H200: "Explosivo inestable.",
  H201: "Explosivo; peligro de explosión en masa.",
  H202: "Explosivo; grave peligro de proyección.",
  H203: "Explosivo; peligro de incendio, de onda expansiva o de proyección.",
  H204: "Peligro de incendio o de proyección.",
  H205: "Peligro de explosión en masa en caso de incendio.",
  H220: "Gas extremadamente inflamable.",
  H221: "Gas inflamable.",
  H222: "Aerosol extremadamente inflamable.",
  H223: "Aerosol inflamable.",
  H224: "Líquido y vapores extremadamente inflamables.",
  H225: "Líquido y vapores muy inflamables.",
  H226: "Líquido y vapores inflamables.",
  H227: "Líquido combustible.",
  H228: "Sólido inflamable.",
  H229: "Recipiente a presión: puede reventar si se calienta.",
  H230: "Puede reaccionar explosivamente incluso en ausencia de aire.",
  H231: "Puede reaccionar explosivamente incluso en ausencia de aire a presión elevada o temperatura elevada.",
  H232: "Puede inflamarse espontáneamente en contacto con el aire.",
  H240: "Peligro de explosión en caso de calentamiento.",
  H241: "Peligro de incendio o explosión en caso de calentamiento.",
  H242: "Peligro de incendio en caso de calentamiento.",
  H250: "Se inflama espontáneamente en contacto con el aire.",
  H251: "Se calienta espontáneamente; puede inflamarse.",
  H252: "Se calienta espontáneamente en grandes cantidades; puede inflamarse.",
  H260: "En contacto con el agua desprende gases inflamables que pueden inflamarse espontáneamente.",
  H261: "En contacto con el agua desprende gases inflamables.",
  H270: "Puede provocar o agravar un incendio; comburente.",
  H271: "Puede provocar un incendio o una explosión; muy comburente.",
  H272: "Puede agravar un incendio; comburente.",
  H280: "Contiene gas a presión; peligro de explosión en caso de calentamiento.",
  H281: "Contiene un gas refrigerado; puede provocar quemaduras o lesiones criogénicas.",
  H290: "Puede ser corrosivo para los metales.",

  // Peligros para la salud (H300-H373)
  H300: "Mortal en caso de ingestión.",
  H301: "Tóxico en caso de ingestión.",
  H302: "Nocivo en caso de ingestión.",
  H303: "Puede ser nocivo en caso de ingestión.",
  H304: "Puede ser mortal en caso de ingestión y penetración en las vías respiratorias.",
  H305: "Puede ser nocivo en caso de ingestión y penetración en las vías respiratorias.",
  H310: "Mortal en contacto con la piel.",
  H311: "Tóxico en contacto con la piel.",
  H312: "Nocivo en contacto con la piel.",
  H313: "Puede ser nocivo en contacto con la piel.",
  H314: "Provoca quemaduras graves en la piel y lesiones oculares graves.",
  H315: "Provoca irritación cutánea.",
  H316: "Provoca una leve irritación cutánea.",
  H317: "Puede provocar una reacción alérgica en la piel.",
  H318: "Provoca lesiones oculares graves.",
  H319: "Provoca irritación ocular grave.",
  H320: "Provoca irritación ocular.",
  H330: "Mortal en caso de inhalación.",
  H331: "Tóxico en caso de inhalación.",
  H332: "Nocivo en caso de inhalación.",
  H333: "Puede ser nocivo en caso de inhalación.",
  H334: "Puede provocar síntomas de alergia o asma o dificultades respiratorias en caso de inhalación.",
  H335: "Puede irritar las vías respiratorias.",
  H336: "Puede provocar somnolencia o vértigo.",
  H340: "Puede provocar defectos genéticos.",
  H341: "Se sospecha que provoca defectos genéticos.",
  H350: "Puede provocar cáncer.",
  H351: "Se sospecha que provoca cáncer.",
  H360: "Puede perjudicar la fertilidad o dañar al feto.",
  H361: "Se sospecha que perjudica la fertilidad o daña al feto.",
  H362: "Puede perjudicar a los niños alimentados con leche materna.",
  H370: "Provoca daños en los órganos.",
  H371: "Puede provocar daños en los órganos.",
  H372: "Provoca daños en los órganos tras exposiciones prolongadas o repetidas.",
  H373: "Puede provocar daños en los órganos tras exposiciones prolongadas o repetidas.",

  // Peligros para el medio ambiente (H400-H420)
  H400: "Muy tóxico para los organismos acuáticos.",
  H401: "Tóxico para los organismos acuáticos.",
  H402: "Nocivo para los organismos acuáticos.",
  H410: "Muy tóxico para los organismos acuáticos, con efectos nocivos duraderos.",
  H411: "Tóxico para los organismos acuáticos, con efectos nocivos duraderos.",
  H412: "Nocivo para los organismos acuáticos, con efectos nocivos duraderos.",
  H413: "Puede ser nocivo para los organismos acuáticos, con efectos nocivos duraderos.",
  H420: "Perjudica la salud pública y el medio ambiente al destruir el ozono de la alta atmósfera.",
};

export const P_STATEMENTS: Record<string, string> = {
  // Generales (P100)
  P101: "Si se necesita consejo médico, tener a mano el envase o la etiqueta.",
  P102: "Mantener fuera del alcance de los niños.",
  P103: "Leer atentamente y seguir todas las instrucciones.",

  // Prevención (P200)
  P201: "Solicitar instrucciones especiales antes del uso.",
  P202: "No manipular la sustancia antes de haber leído y comprendido todas las instrucciones de seguridad.",
  P210: "Mantener alejado del calor, de superficies calientes, de chispas, de llamas abiertas y de cualquier otra fuente de ignición. No fumar.",
  P211: "No pulverizar sobre una llama abierta u otra fuente de ignición.",
  P212: "Evitar calentar bajo confinamiento o una disminución del agente insensibilizador.",
  P220: "Mantener alejado de la ropa y otros materiales combustibles.",
  P221: "Tomar todas las precauciones necesarias para no mezclar con materias combustibles.",
  P222: "No dejar en contacto con el aire.",
  P223: "Evitar el contacto con el agua.",
  P230: "Mantener humedecido con el material adecuado.",
  P231: "Manipular en gas inerte.",
  P232: "Proteger de la humedad.",
  P233: "Mantener el recipiente herméticamente cerrado.",
  P234: "Conservar únicamente en el embalaje original.",
  P235: "Mantener en lugar fresco.",
  P240: "Conectar a tierra y enlace equipotencial del recipiente y del equipo receptor.",
  P241: "Utilizar material eléctrico, de ventilación o de iluminación antideflagrante.",
  P242: "No utilizar herramientas que produzcan chispas.",
  P243: "Tomar medidas de precaución contra descargas electrostáticas.",
  P244: "Mantener las válvulas y los racores libres de aceite y grasa.",
  P250: "Evitar la abrasión, el choque o la fricción.",
  P251: "No perforar ni quemar, incluso después de su uso.",
  P260: "No respirar el polvo/el humo/el gas/la niebla/los vapores/los aerosoles.",
  P261: "Evitar respirar el polvo/el humo/el gas/la niebla/los vapores/los aerosoles.",
  P262: "Evitar el contacto con los ojos, la piel o la ropa.",
  P263: "Evitar el contacto durante el embarazo y la lactancia.",
  P264: "Lavarse concienzudamente las manos tras la manipulación.",
  P270: "No comer, beber ni fumar durante su utilización.",
  P271: "Utilizar únicamente en exteriores o en un lugar bien ventilado.",
  P272: "Las prendas de trabajo contaminadas no podrán sacarse del lugar de trabajo.",
  P273: "Evitar su liberación al medio ambiente.",
  P280: "Llevar guantes, prendas, gafas o máscara de protección.",
  P282: "Llevar guantes que aíslen del frío y protección facial o ocular.",
  P283: "Llevar ropa ignífuga o retardante de llama.",
  P284: "En caso de ventilación insuficiente, llevar equipo de protección respiratoria.",

  // Intervención (P300) — subconjunto más usado
  P301: "EN CASO DE INGESTIÓN:",
  P302: "EN CASO DE CONTACTO CON LA PIEL:",
  P303: "EN CASO DE CONTACTO CON LA PIEL (o el pelo):",
  P304: "EN CASO DE INHALACIÓN:",
  P305: "EN CASO DE CONTACTO CON LOS OJOS:",
  P306: "EN CASO DE CONTACTO CON LA ROPA:",
  P308: "EN CASO DE exposición manifiesta o presunta:",
  P310: "Llamar inmediatamente a un CENTRO DE TOXICOLOGÍA o a un médico.",
  P311: "Llamar a un CENTRO DE TOXICOLOGÍA o a un médico.",
  P312: "Llamar a un CENTRO DE TOXICOLOGÍA o a un médico en caso de malestar.",
  P313: "Consultar a un médico.",
  P314: "Consultar a un médico en caso de malestar.",
  P315: "Consultar a un médico inmediatamente.",
  P320: "Se necesita urgentemente tratamiento específico.",
  P321: "Se necesita tratamiento específico (ver la etiqueta).",
  P330: "Enjuagarse la boca.",
  P331: "NO provocar el vómito.",
  P332: "En caso de irritación cutánea:",
  P333: "En caso de irritación o erupción cutánea:",
  P334: "Sumergir en agua fría o cubrir con un vendaje húmedo.",
  P335: "Sacudir las partículas sueltas depositadas en la piel.",
  P336: "Descongelar las partes heladas con agua templada. No frotar la zona afectada.",
  P337: "Si persiste la irritación ocular:",
  P338: "Quitar las lentes de contacto cuando estén presentes y pueda hacerse con facilidad. Proseguir con el lavado.",
  P340: "Transportar a la persona al aire libre y mantenerla en una posición que le facilite la respiración.",
  P342: "En caso de síntomas respiratorios:",
  P351: "Aclarar cuidadosamente con agua durante varios minutos.",
  P352: "Lavar con abundante agua.",
  P353: "Aclararse la piel con agua o ducharse.",
  P360: "Aclarar inmediatamente con agua abundante las prendas y la piel contaminadas antes de quitarse la ropa.",
  P361: "Quitar inmediatamente todas las prendas contaminadas.",
  P362: "Quitar las prendas contaminadas.",
  P363: "Lavar las prendas contaminadas antes de volver a usarlas.",
  P364: "Y lavarlas antes de volver a usarlas.",
  P370: "En caso de incendio:",
  P371: "En caso de incendio importante y en grandes cantidades:",
  P372: "Riesgo de explosión.",
  P373: "NO luchar contra el incendio cuando el fuego alcance a los explosivos.",
  P375: "Luchar contra el incendio a distancia, dado el riesgo de explosión.",
  P376: "Detener la fuga, si no hay peligro en hacerlo.",
  P377: "Fuga de gas en llamas: no apagar, salvo si la fuga puede detenerse sin peligro.",
  P378: "Utilizar los medios de extinción adecuados.",
  P380: "Evacuar la zona.",
  P381: "En caso de fuga, eliminar todas las fuentes de ignición.",
  P390: "Absorber el vertido para que no dañe otros materiales.",
  P391: "Recoger el vertido.",

  // Almacenamiento (P400)
  P401: "Almacenar de conformidad con la normativa local.",
  P402: "Almacenar en un lugar seco.",
  P403: "Almacenar en un lugar bien ventilado.",
  P404: "Almacenar en un recipiente cerrado.",
  P405: "Guardar bajo llave.",
  P406: "Almacenar en un recipiente resistente a la corrosión con revestimiento interior resistente.",
  P407: "Dejar espacio entre los bloques/palés de carga.",
  P410: "Proteger de la luz del sol.",
  P411: "Almacenar a temperaturas no superiores a los °C/°F indicados.",
  P412: "No exponer a temperaturas superiores a 50 °C/122 °F.",
  P413: "Almacenar las cantidades a granel superiores a los kg/lbs indicados a temperaturas no superiores a los °C/°F indicados.",
  P420: "Almacenar separadamente.",
  P422: "Almacenar bajo el gas o el líquido inerte indicado.",

  // Eliminación (P500)
  P501: "Eliminar el contenido/el recipiente conforme a la reglamentación local/regional/nacional/internacional.",
  P502: "Pedir información al fabricante o al proveedor sobre su recuperación o reciclado.",
};

// Resolve a potentially combined code (e.g. "H301+H311+H331") into its full text
// by joining the individual statement texts.
export function resolveStatement(
  code: string,
  dict: Record<string, string>
): string {
  if (dict[code]) return dict[code];
  if (code.includes("+")) {
    const parts = code.split("+");
    const texts = parts
      .map((p) => dict[p])
      .filter((t): t is string => Boolean(t));
    if (texts.length > 0) return texts.join(" ");
  }
  return "Texto de la indicación no disponible.";
}
