// Curated list of 100 common industrial chemicals with:
//   - Core identifiers (name, CAS, formula)
//   - OSHA PEL / NIOSH REL / ACGIH TLV where published by NIOSH Pocket Guide
//   - IDLH where published
//   - Key physical properties (BP, FP, IGN, LEL, UEL, density)
// Values from NIOSH Pocket Guide to Chemical Hazards (NPG) and CRC Handbook.
// GHS pictograms + H/P statements are enriched from PubChem at seed time.

export type SeedLimit = {
  authority: string;
  countryCode: string;
  limitType: "TWA" | "STEL" | "Ceiling" | "IDLH";
  ppm?: number;
  mgM3?: number;
  notes?: string;
};

export type SeedPhysical = {
  boilingPointC?: number;
  meltingPointC?: number;
  flashPointC?: number;
  ignitionTempC?: number;
  lelVolPct?: number;
  uelVolPct?: number;
  densityGCm3?: number;
  ionizationEv?: number;
};

export type SeedSubstance = {
  name: string;
  casNumber: string;
  formula?: string;
  unNumber?: string;
  ecNumber?: string;
  limits?: SeedLimit[];
  physical?: SeedPhysical;
};

export const SEED_SUBSTANCES: SeedSubstance[] = [
  {
    name: "Ammonia",
    casNumber: "7664-41-7",
    formula: "NH3",
    unNumber: "1005",
    ecNumber: "231-635-3",
    limits: [
      { authority: "OSHA_PEL", countryCode: "US", limitType: "TWA", ppm: 50, mgM3: 35 },
      { authority: "NIOSH_REL", countryCode: "US", limitType: "TWA", ppm: 25, mgM3: 18 },
      { authority: "NIOSH_REL", countryCode: "US", limitType: "STEL", ppm: 35, mgM3: 27 },
      { authority: "ACGIH_TLV", countryCode: "US", limitType: "TWA", ppm: 25 },
      { authority: "ACGIH_TLV", countryCode: "US", limitType: "STEL", ppm: 35 },
      { authority: "NIOSH", countryCode: "US", limitType: "IDLH", ppm: 300 },
    ],
    physical: {
      boilingPointC: -33.3,
      meltingPointC: -77.7,
      lelVolPct: 15,
      uelVolPct: 28,
      densityGCm3: 0.00073,
      ionizationEv: 10.18,
    },
  },
  {
    name: "Hydrogen sulfide",
    casNumber: "7783-06-4",
    formula: "H2S",
    unNumber: "1053",
    ecNumber: "231-977-3",
    limits: [
      { authority: "OSHA_PEL", countryCode: "US", limitType: "Ceiling", ppm: 20 },
      { authority: "NIOSH_REL", countryCode: "US", limitType: "Ceiling", ppm: 10, mgM3: 15 },
      { authority: "ACGIH_TLV", countryCode: "US", limitType: "TWA", ppm: 1 },
      { authority: "ACGIH_TLV", countryCode: "US", limitType: "STEL", ppm: 5 },
      { authority: "NIOSH", countryCode: "US", limitType: "IDLH", ppm: 100 },
    ],
    physical: {
      boilingPointC: -60.3,
      meltingPointC: -85.5,
      lelVolPct: 4,
      uelVolPct: 44,
      ignitionTempC: 260,
      ionizationEv: 10.45,
    },
  },
  {
    name: "Chlorine",
    casNumber: "7782-50-5",
    formula: "Cl2",
    unNumber: "1017",
    ecNumber: "231-959-5",
    limits: [
      { authority: "OSHA_PEL", countryCode: "US", limitType: "Ceiling", ppm: 1, mgM3: 3 },
      { authority: "NIOSH_REL", countryCode: "US", limitType: "Ceiling", ppm: 0.5, mgM3: 1.45 },
      { authority: "ACGIH_TLV", countryCode: "US", limitType: "TWA", ppm: 0.1 },
      { authority: "ACGIH_TLV", countryCode: "US", limitType: "STEL", ppm: 0.4 },
      { authority: "NIOSH", countryCode: "US", limitType: "IDLH", ppm: 10 },
    ],
    physical: {
      boilingPointC: -34.0,
      meltingPointC: -101,
      densityGCm3: 0.0032,
      ionizationEv: 11.48,
    },
  },
  {
    name: "Carbon monoxide",
    casNumber: "630-08-0",
    formula: "CO",
    unNumber: "1016",
    ecNumber: "211-128-3",
    limits: [
      { authority: "OSHA_PEL", countryCode: "US", limitType: "TWA", ppm: 50, mgM3: 55 },
      { authority: "NIOSH_REL", countryCode: "US", limitType: "TWA", ppm: 35, mgM3: 40 },
      { authority: "NIOSH_REL", countryCode: "US", limitType: "Ceiling", ppm: 200 },
      { authority: "ACGIH_TLV", countryCode: "US", limitType: "TWA", ppm: 25 },
      { authority: "NIOSH", countryCode: "US", limitType: "IDLH", ppm: 1200 },
    ],
    physical: {
      boilingPointC: -191.5,
      meltingPointC: -205,
      lelVolPct: 12.5,
      uelVolPct: 74,
      ignitionTempC: 609,
      ionizationEv: 14.01,
    },
  },
  {
    name: "Hydrogen chloride",
    casNumber: "7647-01-0",
    formula: "HCl",
    unNumber: "1050",
    ecNumber: "231-595-7",
    limits: [
      { authority: "OSHA_PEL", countryCode: "US", limitType: "Ceiling", ppm: 5, mgM3: 7 },
      { authority: "NIOSH_REL", countryCode: "US", limitType: "Ceiling", ppm: 5, mgM3: 7 },
      { authority: "ACGIH_TLV", countryCode: "US", limitType: "Ceiling", ppm: 2 },
      { authority: "NIOSH", countryCode: "US", limitType: "IDLH", ppm: 50 },
    ],
    physical: {
      boilingPointC: -85,
      meltingPointC: -114,
      ionizationEv: 12.74,
    },
  },
  {
    name: "Sulfur dioxide",
    casNumber: "7446-09-5",
    formula: "SO2",
    unNumber: "1079",
    ecNumber: "231-195-2",
    limits: [
      { authority: "OSHA_PEL", countryCode: "US", limitType: "TWA", ppm: 5, mgM3: 13 },
      { authority: "NIOSH_REL", countryCode: "US", limitType: "TWA", ppm: 2, mgM3: 5 },
      { authority: "NIOSH_REL", countryCode: "US", limitType: "STEL", ppm: 5, mgM3: 13 },
      { authority: "ACGIH_TLV", countryCode: "US", limitType: "STEL", ppm: 0.25 },
      { authority: "NIOSH", countryCode: "US", limitType: "IDLH", ppm: 100 },
    ],
    physical: {
      boilingPointC: -10,
      meltingPointC: -75.5,
      ionizationEv: 12.32,
    },
  },
  {
    name: "Phenol",
    casNumber: "108-95-2",
    formula: "C6H6O",
    unNumber: "1671",
    ecNumber: "203-632-7",
    limits: [
      { authority: "OSHA_PEL", countryCode: "US", limitType: "TWA", ppm: 5, mgM3: 19 },
      { authority: "NIOSH_REL", countryCode: "US", limitType: "TWA", ppm: 5, mgM3: 19 },
      { authority: "NIOSH_REL", countryCode: "US", limitType: "Ceiling", ppm: 15.6, mgM3: 60, notes: "15min" },
      { authority: "ACGIH_TLV", countryCode: "US", limitType: "TWA", ppm: 5 },
      { authority: "NIOSH", countryCode: "US", limitType: "IDLH", ppm: 250 },
    ],
    physical: {
      boilingPointC: 181.8,
      meltingPointC: 40.9,
      flashPointC: 79,
      ignitionTempC: 715,
      lelVolPct: 1.8,
      uelVolPct: 8.6,
      densityGCm3: 1.06,
      ionizationEv: 8.5,
    },
  },
  {
    name: "Benzene",
    casNumber: "71-43-2",
    formula: "C6H6",
    unNumber: "1114",
    ecNumber: "200-753-7",
    limits: [
      { authority: "OSHA_PEL", countryCode: "US", limitType: "TWA", ppm: 1, mgM3: 3.19 },
      { authority: "OSHA_PEL", countryCode: "US", limitType: "STEL", ppm: 5 },
      { authority: "NIOSH_REL", countryCode: "US", limitType: "TWA", ppm: 0.1 },
      { authority: "NIOSH_REL", countryCode: "US", limitType: "STEL", ppm: 1 },
      { authority: "ACGIH_TLV", countryCode: "US", limitType: "TWA", ppm: 0.5 },
      { authority: "ACGIH_TLV", countryCode: "US", limitType: "STEL", ppm: 2.5 },
      { authority: "NIOSH", countryCode: "US", limitType: "IDLH", ppm: 500 },
    ],
    physical: {
      boilingPointC: 80.1,
      meltingPointC: 5.5,
      flashPointC: -11,
      ignitionTempC: 498,
      lelVolPct: 1.2,
      uelVolPct: 7.8,
      densityGCm3: 0.879,
      ionizationEv: 9.24,
    },
  },
  {
    name: "Toluene",
    casNumber: "108-88-3",
    formula: "C7H8",
    unNumber: "1294",
    ecNumber: "203-625-9",
    limits: [
      { authority: "OSHA_PEL", countryCode: "US", limitType: "TWA", ppm: 200, mgM3: 754 },
      { authority: "NIOSH_REL", countryCode: "US", limitType: "TWA", ppm: 100, mgM3: 375 },
      { authority: "NIOSH_REL", countryCode: "US", limitType: "STEL", ppm: 150, mgM3: 560 },
      { authority: "ACGIH_TLV", countryCode: "US", limitType: "TWA", ppm: 20 },
      { authority: "NIOSH", countryCode: "US", limitType: "IDLH", ppm: 500 },
    ],
    physical: {
      boilingPointC: 110.6,
      meltingPointC: -95,
      flashPointC: 4,
      ignitionTempC: 480,
      lelVolPct: 1.1,
      uelVolPct: 7.1,
      densityGCm3: 0.867,
      ionizationEv: 8.82,
    },
  },
  {
    name: "Xylene",
    casNumber: "1330-20-7",
    formula: "C8H10",
    unNumber: "1307",
    ecNumber: "215-535-7",
    limits: [
      { authority: "OSHA_PEL", countryCode: "US", limitType: "TWA", ppm: 100, mgM3: 435 },
      { authority: "NIOSH_REL", countryCode: "US", limitType: "TWA", ppm: 100, mgM3: 435 },
      { authority: "NIOSH_REL", countryCode: "US", limitType: "STEL", ppm: 150, mgM3: 655 },
      { authority: "ACGIH_TLV", countryCode: "US", limitType: "TWA", ppm: 100 },
      { authority: "ACGIH_TLV", countryCode: "US", limitType: "STEL", ppm: 150 },
      { authority: "NIOSH", countryCode: "US", limitType: "IDLH", ppm: 900 },
    ],
    physical: {
      boilingPointC: 138.5,
      flashPointC: 27,
      ignitionTempC: 464,
      lelVolPct: 1.1,
      uelVolPct: 7,
      densityGCm3: 0.864,
      ionizationEv: 8.56,
    },
  },
  {
    name: "Acetone",
    casNumber: "67-64-1",
    formula: "C3H6O",
    unNumber: "1090",
    ecNumber: "200-662-2",
    limits: [
      { authority: "OSHA_PEL", countryCode: "US", limitType: "TWA", ppm: 1000, mgM3: 2400 },
      { authority: "NIOSH_REL", countryCode: "US", limitType: "TWA", ppm: 250, mgM3: 590 },
      { authority: "ACGIH_TLV", countryCode: "US", limitType: "TWA", ppm: 250 },
      { authority: "ACGIH_TLV", countryCode: "US", limitType: "STEL", ppm: 500 },
      { authority: "NIOSH", countryCode: "US", limitType: "IDLH", ppm: 2500 },
    ],
    physical: {
      boilingPointC: 56,
      meltingPointC: -94.7,
      flashPointC: -20,
      ignitionTempC: 465,
      lelVolPct: 2.5,
      uelVolPct: 12.8,
      densityGCm3: 0.791,
      ionizationEv: 9.69,
    },
  },
  {
    name: "Methanol",
    casNumber: "67-56-1",
    formula: "CH4O",
    unNumber: "1230",
    ecNumber: "200-659-6",
    limits: [
      { authority: "OSHA_PEL", countryCode: "US", limitType: "TWA", ppm: 200, mgM3: 260 },
      { authority: "NIOSH_REL", countryCode: "US", limitType: "TWA", ppm: 200, mgM3: 260 },
      { authority: "NIOSH_REL", countryCode: "US", limitType: "STEL", ppm: 250, mgM3: 325 },
      { authority: "ACGIH_TLV", countryCode: "US", limitType: "TWA", ppm: 200 },
      { authority: "ACGIH_TLV", countryCode: "US", limitType: "STEL", ppm: 250 },
      { authority: "NIOSH", countryCode: "US", limitType: "IDLH", ppm: 6000 },
    ],
    physical: {
      boilingPointC: 64.7,
      meltingPointC: -97.7,
      flashPointC: 11,
      ignitionTempC: 385,
      lelVolPct: 6,
      uelVolPct: 36,
      densityGCm3: 0.791,
      ionizationEv: 10.85,
    },
  },
  {
    name: "Ethanol",
    casNumber: "64-17-5",
    formula: "C2H6O",
    unNumber: "1170",
    ecNumber: "200-578-6",
    limits: [
      { authority: "OSHA_PEL", countryCode: "US", limitType: "TWA", ppm: 1000, mgM3: 1900 },
      { authority: "ACGIH_TLV", countryCode: "US", limitType: "STEL", ppm: 1000 },
      { authority: "NIOSH", countryCode: "US", limitType: "IDLH", ppm: 3300 },
    ],
    physical: {
      boilingPointC: 78.3,
      meltingPointC: -114,
      flashPointC: 13,
      ignitionTempC: 363,
      lelVolPct: 3.3,
      uelVolPct: 19,
      densityGCm3: 0.789,
      ionizationEv: 10.47,
    },
  },
  {
    name: "Formaldehyde",
    casNumber: "50-00-0",
    formula: "CH2O",
    unNumber: "2209",
    ecNumber: "200-001-8",
    limits: [
      { authority: "OSHA_PEL", countryCode: "US", limitType: "TWA", ppm: 0.75 },
      { authority: "OSHA_PEL", countryCode: "US", limitType: "STEL", ppm: 2 },
      { authority: "NIOSH_REL", countryCode: "US", limitType: "Ceiling", ppm: 0.1 },
      { authority: "ACGIH_TLV", countryCode: "US", limitType: "Ceiling", ppm: 0.3 },
      { authority: "NIOSH", countryCode: "US", limitType: "IDLH", ppm: 20 },
    ],
    physical: {
      boilingPointC: -19.5,
      meltingPointC: -92,
      flashPointC: 64,
      ignitionTempC: 430,
      lelVolPct: 7,
      uelVolPct: 73,
      ionizationEv: 10.88,
    },
  },
  {
    name: "Nitric acid",
    casNumber: "7697-37-2",
    formula: "HNO3",
    unNumber: "2031",
    ecNumber: "231-714-2",
    limits: [
      { authority: "OSHA_PEL", countryCode: "US", limitType: "TWA", ppm: 2, mgM3: 5 },
      { authority: "NIOSH_REL", countryCode: "US", limitType: "TWA", ppm: 2, mgM3: 5 },
      { authority: "NIOSH_REL", countryCode: "US", limitType: "STEL", ppm: 4, mgM3: 10 },
      { authority: "ACGIH_TLV", countryCode: "US", limitType: "TWA", ppm: 2 },
      { authority: "NIOSH", countryCode: "US", limitType: "IDLH", ppm: 25 },
    ],
    physical: { boilingPointC: 83, meltingPointC: -42, densityGCm3: 1.5 },
  },
  {
    name: "Sulfuric acid",
    casNumber: "7664-93-9",
    formula: "H2SO4",
    unNumber: "1830",
    ecNumber: "231-639-5",
    limits: [
      { authority: "OSHA_PEL", countryCode: "US", limitType: "TWA", mgM3: 1 },
      { authority: "NIOSH_REL", countryCode: "US", limitType: "TWA", mgM3: 1 },
      { authority: "ACGIH_TLV", countryCode: "US", limitType: "TWA", mgM3: 0.2 },
      { authority: "NIOSH", countryCode: "US", limitType: "IDLH", mgM3: 15 },
    ],
    physical: { boilingPointC: 337, meltingPointC: 10.4, densityGCm3: 1.84 },
  },
  {
    name: "Hydrogen cyanide",
    casNumber: "74-90-8",
    formula: "HCN",
    unNumber: "1051",
    ecNumber: "200-821-6",
    limits: [
      { authority: "OSHA_PEL", countryCode: "US", limitType: "TWA", ppm: 10, mgM3: 11 },
      { authority: "NIOSH_REL", countryCode: "US", limitType: "STEL", ppm: 4.7, mgM3: 5 },
      { authority: "ACGIH_TLV", countryCode: "US", limitType: "Ceiling", ppm: 4.7 },
      { authority: "NIOSH", countryCode: "US", limitType: "IDLH", ppm: 50 },
    ],
    physical: {
      boilingPointC: 25.7,
      flashPointC: -17.8,
      ignitionTempC: 538,
      lelVolPct: 5.6,
      uelVolPct: 40,
      ionizationEv: 13.6,
    },
  },
  {
    name: "Acetaldehyde",
    casNumber: "75-07-0",
    formula: "C2H4O",
    unNumber: "1089",
    ecNumber: "200-836-8",
    limits: [
      { authority: "OSHA_PEL", countryCode: "US", limitType: "TWA", ppm: 200, mgM3: 360 },
      { authority: "ACGIH_TLV", countryCode: "US", limitType: "Ceiling", ppm: 25 },
      { authority: "NIOSH", countryCode: "US", limitType: "IDLH", ppm: 2000 },
    ],
    physical: {
      boilingPointC: 20.8,
      flashPointC: -39,
      ignitionTempC: 175,
      lelVolPct: 4,
      uelVolPct: 60,
      densityGCm3: 0.778,
    },
  },
  {
    name: "Acetic acid",
    casNumber: "64-19-7",
    formula: "C2H4O2",
    unNumber: "2789",
    ecNumber: "200-580-7",
    limits: [
      { authority: "OSHA_PEL", countryCode: "US", limitType: "TWA", ppm: 10, mgM3: 25 },
      { authority: "NIOSH_REL", countryCode: "US", limitType: "TWA", ppm: 10, mgM3: 25 },
      { authority: "NIOSH_REL", countryCode: "US", limitType: "STEL", ppm: 15, mgM3: 37 },
      { authority: "ACGIH_TLV", countryCode: "US", limitType: "TWA", ppm: 10 },
      { authority: "NIOSH", countryCode: "US", limitType: "IDLH", ppm: 50 },
    ],
    physical: {
      boilingPointC: 118,
      meltingPointC: 16.6,
      flashPointC: 39,
      ignitionTempC: 427,
      lelVolPct: 4,
      uelVolPct: 19.9,
      densityGCm3: 1.049,
    },
  },
  {
    name: "Acrolein",
    casNumber: "107-02-8",
    formula: "C3H4O",
    unNumber: "1092",
    ecNumber: "203-453-4",
    limits: [
      { authority: "OSHA_PEL", countryCode: "US", limitType: "TWA", ppm: 0.1, mgM3: 0.25 },
      { authority: "NIOSH_REL", countryCode: "US", limitType: "TWA", ppm: 0.1 },
      { authority: "NIOSH_REL", countryCode: "US", limitType: "STEL", ppm: 0.3 },
      { authority: "ACGIH_TLV", countryCode: "US", limitType: "Ceiling", ppm: 0.1 },
      { authority: "NIOSH", countryCode: "US", limitType: "IDLH", ppm: 2 },
    ],
    physical: {
      boilingPointC: 52.5,
      flashPointC: -26,
      ignitionTempC: 234,
      lelVolPct: 2.8,
      uelVolPct: 31,
      densityGCm3: 0.843,
    },
  },
  { name: "Acrylonitrile", casNumber: "107-13-1", formula: "C3H3N", unNumber: "1093", limits: [
    { authority: "OSHA_PEL", countryCode: "US", limitType: "TWA", ppm: 2 },
    { authority: "NIOSH_REL", countryCode: "US", limitType: "TWA", ppm: 1 },
    { authority: "NIOSH", countryCode: "US", limitType: "IDLH", ppm: 85 },
  ], physical: { boilingPointC: 77, flashPointC: 0, lelVolPct: 3, uelVolPct: 17, densityGCm3: 0.806 } },
  { name: "Arsine", casNumber: "7784-42-1", formula: "AsH3", unNumber: "2188", limits: [
    { authority: "OSHA_PEL", countryCode: "US", limitType: "TWA", ppm: 0.05, mgM3: 0.2 },
    { authority: "NIOSH_REL", countryCode: "US", limitType: "Ceiling", ppm: 0.002 },
    { authority: "ACGIH_TLV", countryCode: "US", limitType: "TWA", ppm: 0.005 },
    { authority: "NIOSH", countryCode: "US", limitType: "IDLH", ppm: 3 },
  ], physical: { boilingPointC: -62.5, ignitionTempC: 280 } },
  { name: "Benzonitrile", casNumber: "100-47-0", formula: "C7H5N", physical: { boilingPointC: 191, flashPointC: 75, densityGCm3: 1.01 } },
  { name: "Bromine", casNumber: "7726-95-6", formula: "Br2", unNumber: "1744", limits: [
    { authority: "OSHA_PEL", countryCode: "US", limitType: "TWA", ppm: 0.1, mgM3: 0.7 },
    { authority: "NIOSH_REL", countryCode: "US", limitType: "STEL", ppm: 0.3 },
    { authority: "ACGIH_TLV", countryCode: "US", limitType: "TWA", ppm: 0.1 },
    { authority: "NIOSH", countryCode: "US", limitType: "IDLH", ppm: 3 },
  ], physical: { boilingPointC: 58.8, meltingPointC: -7.2, densityGCm3: 3.12 } },
  { name: "Butadiene", casNumber: "106-99-0", formula: "C4H6", unNumber: "1010", limits: [
    { authority: "OSHA_PEL", countryCode: "US", limitType: "TWA", ppm: 1 },
    { authority: "NIOSH_REL", countryCode: "US", limitType: "TWA", ppm: 1 },
    { authority: "ACGIH_TLV", countryCode: "US", limitType: "TWA", ppm: 2 },
    { authority: "NIOSH", countryCode: "US", limitType: "IDLH", ppm: 2000 },
  ], physical: { boilingPointC: -4.4, flashPointC: -76, lelVolPct: 2, uelVolPct: 12 } },
  { name: "Butane", casNumber: "106-97-8", formula: "C4H10", unNumber: "1011", limits: [
    { authority: "NIOSH_REL", countryCode: "US", limitType: "TWA", ppm: 800, mgM3: 1900 },
    { authority: "ACGIH_TLV", countryCode: "US", limitType: "STEL", ppm: 1000 },
  ], physical: { boilingPointC: -0.5, flashPointC: -60, ignitionTempC: 287, lelVolPct: 1.6, uelVolPct: 8.4 } },
  { name: "Carbon dioxide", casNumber: "124-38-9", formula: "CO2", unNumber: "1013", limits: [
    { authority: "OSHA_PEL", countryCode: "US", limitType: "TWA", ppm: 5000 },
    { authority: "NIOSH_REL", countryCode: "US", limitType: "TWA", ppm: 5000 },
    { authority: "NIOSH_REL", countryCode: "US", limitType: "STEL", ppm: 30000 },
    { authority: "NIOSH", countryCode: "US", limitType: "IDLH", ppm: 40000 },
  ], physical: { boilingPointC: -78.5 } },
  { name: "Carbon disulfide", casNumber: "75-15-0", formula: "CS2", unNumber: "1131", limits: [
    { authority: "OSHA_PEL", countryCode: "US", limitType: "TWA", ppm: 20 },
    { authority: "NIOSH_REL", countryCode: "US", limitType: "TWA", ppm: 1, mgM3: 3 },
    { authority: "NIOSH_REL", countryCode: "US", limitType: "STEL", ppm: 10, mgM3: 30 },
    { authority: "ACGIH_TLV", countryCode: "US", limitType: "TWA", ppm: 1 },
    { authority: "NIOSH", countryCode: "US", limitType: "IDLH", ppm: 500 },
  ], physical: { boilingPointC: 46.3, flashPointC: -30, ignitionTempC: 90, lelVolPct: 1.3, uelVolPct: 50 } },
  { name: "Carbon tetrachloride", casNumber: "56-23-5", formula: "CCl4", unNumber: "1846", limits: [
    { authority: "OSHA_PEL", countryCode: "US", limitType: "TWA", ppm: 10 },
    { authority: "NIOSH_REL", countryCode: "US", limitType: "STEL", ppm: 2, mgM3: 12.6, notes: "60min" },
    { authority: "ACGIH_TLV", countryCode: "US", limitType: "TWA", ppm: 5 },
    { authority: "NIOSH", countryCode: "US", limitType: "IDLH", ppm: 200 },
  ], physical: { boilingPointC: 76.7, densityGCm3: 1.59 } },
  { name: "Chloroform", casNumber: "67-66-3", formula: "CHCl3", unNumber: "1888", limits: [
    { authority: "OSHA_PEL", countryCode: "US", limitType: "Ceiling", ppm: 50 },
    { authority: "NIOSH_REL", countryCode: "US", limitType: "STEL", ppm: 2, mgM3: 9.78, notes: "60min" },
    { authority: "ACGIH_TLV", countryCode: "US", limitType: "TWA", ppm: 10 },
    { authority: "NIOSH", countryCode: "US", limitType: "IDLH", ppm: 500 },
  ], physical: { boilingPointC: 61.2, densityGCm3: 1.48 } },
  { name: "Chlorine dioxide", casNumber: "10049-04-4", formula: "ClO2", limits: [
    { authority: "OSHA_PEL", countryCode: "US", limitType: "TWA", ppm: 0.1, mgM3: 0.3 },
    { authority: "NIOSH_REL", countryCode: "US", limitType: "TWA", ppm: 0.1 },
    { authority: "NIOSH_REL", countryCode: "US", limitType: "STEL", ppm: 0.3 },
    { authority: "NIOSH", countryCode: "US", limitType: "IDLH", ppm: 5 },
  ], physical: { boilingPointC: 11 } },
  { name: "Cyclohexane", casNumber: "110-82-7", formula: "C6H12", unNumber: "1145", limits: [
    { authority: "OSHA_PEL", countryCode: "US", limitType: "TWA", ppm: 300 },
    { authority: "NIOSH_REL", countryCode: "US", limitType: "TWA", ppm: 300, mgM3: 1050 },
    { authority: "ACGIH_TLV", countryCode: "US", limitType: "TWA", ppm: 100 },
    { authority: "NIOSH", countryCode: "US", limitType: "IDLH", ppm: 1300 },
  ], physical: { boilingPointC: 80.7, flashPointC: -20, ignitionTempC: 245, lelVolPct: 1.3, uelVolPct: 8, densityGCm3: 0.779 } },
  { name: "Diborane", casNumber: "19287-45-7", formula: "B2H6", unNumber: "1911", limits: [
    { authority: "OSHA_PEL", countryCode: "US", limitType: "TWA", ppm: 0.1, mgM3: 0.1 },
    { authority: "NIOSH", countryCode: "US", limitType: "IDLH", ppm: 15 },
  ], physical: { boilingPointC: -92.5, ignitionTempC: 38 } },
  { name: "Dichloromethane", casNumber: "75-09-2", formula: "CH2Cl2", unNumber: "1593", limits: [
    { authority: "OSHA_PEL", countryCode: "US", limitType: "TWA", ppm: 25 },
    { authority: "ACGIH_TLV", countryCode: "US", limitType: "TWA", ppm: 50 },
    { authority: "NIOSH", countryCode: "US", limitType: "IDLH", ppm: 2300 },
  ], physical: { boilingPointC: 39.6, densityGCm3: 1.326 } },
  { name: "Diesel fuel", casNumber: "68334-30-5", physical: { boilingPointC: 250, flashPointC: 62 } },
  { name: "Dimethylformamide", casNumber: "68-12-2", formula: "C3H7NO", unNumber: "2265", limits: [
    { authority: "OSHA_PEL", countryCode: "US", limitType: "TWA", ppm: 10, mgM3: 30 },
    { authority: "NIOSH_REL", countryCode: "US", limitType: "TWA", ppm: 10, mgM3: 30 },
    { authority: "ACGIH_TLV", countryCode: "US", limitType: "TWA", ppm: 10 },
    { authority: "NIOSH", countryCode: "US", limitType: "IDLH", ppm: 500 },
  ], physical: { boilingPointC: 153, flashPointC: 58, densityGCm3: 0.944 } },
  { name: "Ethylene oxide", casNumber: "75-21-8", formula: "C2H4O", unNumber: "1040", limits: [
    { authority: "OSHA_PEL", countryCode: "US", limitType: "TWA", ppm: 1 },
    { authority: "NIOSH_REL", countryCode: "US", limitType: "TWA", ppm: 0.1 },
    { authority: "NIOSH", countryCode: "US", limitType: "IDLH", ppm: 800 },
  ], physical: { boilingPointC: 10.7, flashPointC: -29, lelVolPct: 3, uelVolPct: 100 } },
  { name: "Ethyl acetate", casNumber: "141-78-6", formula: "C4H8O2", unNumber: "1173", limits: [
    { authority: "OSHA_PEL", countryCode: "US", limitType: "TWA", ppm: 400, mgM3: 1400 },
    { authority: "ACGIH_TLV", countryCode: "US", limitType: "TWA", ppm: 400 },
    { authority: "NIOSH", countryCode: "US", limitType: "IDLH", ppm: 2000 },
  ], physical: { boilingPointC: 77, flashPointC: -4, ignitionTempC: 427, lelVolPct: 2, uelVolPct: 11.5, densityGCm3: 0.902 } },
  { name: "Ethyl ether", casNumber: "60-29-7", formula: "C4H10O", unNumber: "1155", limits: [
    { authority: "OSHA_PEL", countryCode: "US", limitType: "TWA", ppm: 400, mgM3: 1200 },
    { authority: "NIOSH_REL", countryCode: "US", limitType: "TWA", ppm: 400, mgM3: 1200 },
    { authority: "NIOSH_REL", countryCode: "US", limitType: "STEL", ppm: 500, mgM3: 1500 },
    { authority: "NIOSH", countryCode: "US", limitType: "IDLH", ppm: 1900 },
  ], physical: { boilingPointC: 34.6, flashPointC: -45, ignitionTempC: 160, lelVolPct: 1.9, uelVolPct: 36, densityGCm3: 0.713 } },
  { name: "Fluorine", casNumber: "7782-41-4", formula: "F2", unNumber: "1045", limits: [
    { authority: "OSHA_PEL", countryCode: "US", limitType: "TWA", ppm: 0.1 },
    { authority: "NIOSH_REL", countryCode: "US", limitType: "TWA", ppm: 0.1 },
    { authority: "NIOSH_REL", countryCode: "US", limitType: "STEL", ppm: 0.2 },
    { authority: "NIOSH", countryCode: "US", limitType: "IDLH", ppm: 25 },
  ], physical: { boilingPointC: -188 } },
  { name: "Gasoline", casNumber: "8006-61-9", unNumber: "1203", limits: [
    { authority: "ACGIH_TLV", countryCode: "US", limitType: "TWA", ppm: 300 },
    { authority: "ACGIH_TLV", countryCode: "US", limitType: "STEL", ppm: 500 },
  ], physical: { boilingPointC: 38, flashPointC: -43, ignitionTempC: 280, lelVolPct: 1.4, uelVolPct: 7.6 } },
  { name: "Glyoxal", casNumber: "107-22-2", formula: "C2H2O2", physical: { boilingPointC: 50.4, flashPointC: 57 } },
  { name: "Heptane", casNumber: "142-82-5", formula: "C7H16", unNumber: "1206", limits: [
    { authority: "OSHA_PEL", countryCode: "US", limitType: "TWA", ppm: 500 },
    { authority: "NIOSH_REL", countryCode: "US", limitType: "TWA", ppm: 85 },
    { authority: "NIOSH_REL", countryCode: "US", limitType: "Ceiling", ppm: 440, notes: "15min" },
    { authority: "ACGIH_TLV", countryCode: "US", limitType: "TWA", ppm: 400 },
    { authority: "NIOSH", countryCode: "US", limitType: "IDLH", ppm: 750 },
  ], physical: { boilingPointC: 98.4, flashPointC: -4, ignitionTempC: 204, lelVolPct: 1.05, uelVolPct: 6.7, densityGCm3: 0.684 } },
  { name: "Hexane", casNumber: "110-54-3", formula: "C6H14", unNumber: "1208", limits: [
    { authority: "OSHA_PEL", countryCode: "US", limitType: "TWA", ppm: 500 },
    { authority: "NIOSH_REL", countryCode: "US", limitType: "TWA", ppm: 50 },
    { authority: "ACGIH_TLV", countryCode: "US", limitType: "TWA", ppm: 50 },
    { authority: "NIOSH", countryCode: "US", limitType: "IDLH", ppm: 1100 },
  ], physical: { boilingPointC: 68.7, flashPointC: -22, ignitionTempC: 225, lelVolPct: 1.1, uelVolPct: 7.5, densityGCm3: 0.659 } },
  { name: "Hydrazine", casNumber: "302-01-2", formula: "H4N2", unNumber: "2029", limits: [
    { authority: "OSHA_PEL", countryCode: "US", limitType: "TWA", ppm: 1 },
    { authority: "NIOSH_REL", countryCode: "US", limitType: "Ceiling", ppm: 0.03, notes: "120min" },
    { authority: "ACGIH_TLV", countryCode: "US", limitType: "TWA", ppm: 0.01 },
    { authority: "NIOSH", countryCode: "US", limitType: "IDLH", ppm: 50 },
  ], physical: { boilingPointC: 113.5, flashPointC: 38, ignitionTempC: 270 } },
  { name: "Hydrogen", casNumber: "1333-74-0", formula: "H2", unNumber: "1049", physical: { boilingPointC: -252.8, flashPointC: -253, ignitionTempC: 500, lelVolPct: 4, uelVolPct: 75 } },
  { name: "Hydrogen bromide", casNumber: "10035-10-6", formula: "HBr", unNumber: "1048", limits: [
    { authority: "OSHA_PEL", countryCode: "US", limitType: "Ceiling", ppm: 3, mgM3: 10 },
    { authority: "NIOSH_REL", countryCode: "US", limitType: "Ceiling", ppm: 3, mgM3: 10 },
    { authority: "NIOSH", countryCode: "US", limitType: "IDLH", ppm: 30 },
  ], physical: { boilingPointC: -67 } },
  { name: "Hydrogen fluoride", casNumber: "7664-39-3", formula: "HF", unNumber: "1052", limits: [
    { authority: "OSHA_PEL", countryCode: "US", limitType: "TWA", ppm: 3 },
    { authority: "NIOSH_REL", countryCode: "US", limitType: "TWA", ppm: 3, mgM3: 2.5 },
    { authority: "NIOSH_REL", countryCode: "US", limitType: "Ceiling", ppm: 6, mgM3: 5 },
    { authority: "ACGIH_TLV", countryCode: "US", limitType: "Ceiling", ppm: 2 },
    { authority: "NIOSH", countryCode: "US", limitType: "IDLH", ppm: 30 },
  ], physical: { boilingPointC: 19.5 } },
  { name: "Iodine", casNumber: "7553-56-2", formula: "I2", unNumber: "3495", limits: [
    { authority: "OSHA_PEL", countryCode: "US", limitType: "Ceiling", ppm: 0.1 },
    { authority: "NIOSH_REL", countryCode: "US", limitType: "Ceiling", ppm: 0.1 },
    { authority: "NIOSH", countryCode: "US", limitType: "IDLH", ppm: 2 },
  ], physical: { boilingPointC: 184, meltingPointC: 114 } },
  { name: "Isopropanol", casNumber: "67-63-0", formula: "C3H8O", unNumber: "1219", limits: [
    { authority: "OSHA_PEL", countryCode: "US", limitType: "TWA", ppm: 400, mgM3: 980 },
    { authority: "NIOSH_REL", countryCode: "US", limitType: "TWA", ppm: 400 },
    { authority: "NIOSH_REL", countryCode: "US", limitType: "STEL", ppm: 500 },
    { authority: "ACGIH_TLV", countryCode: "US", limitType: "TWA", ppm: 200 },
    { authority: "NIOSH", countryCode: "US", limitType: "IDLH", ppm: 2000 },
  ], physical: { boilingPointC: 82.5, flashPointC: 12, ignitionTempC: 399, lelVolPct: 2, uelVolPct: 12.7, densityGCm3: 0.785 } },
  { name: "Mercury", casNumber: "7439-97-6", formula: "Hg", unNumber: "2809", limits: [
    { authority: "OSHA_PEL", countryCode: "US", limitType: "Ceiling", mgM3: 0.1 },
    { authority: "NIOSH_REL", countryCode: "US", limitType: "TWA", mgM3: 0.05 },
    { authority: "ACGIH_TLV", countryCode: "US", limitType: "TWA", mgM3: 0.025 },
    { authority: "NIOSH", countryCode: "US", limitType: "IDLH", mgM3: 10 },
  ], physical: { boilingPointC: 356.6, meltingPointC: -38.9, densityGCm3: 13.534 } },
  { name: "Methyl ethyl ketone", casNumber: "78-93-3", formula: "C4H8O", unNumber: "1193", limits: [
    { authority: "OSHA_PEL", countryCode: "US", limitType: "TWA", ppm: 200, mgM3: 590 },
    { authority: "NIOSH_REL", countryCode: "US", limitType: "TWA", ppm: 200 },
    { authority: "NIOSH_REL", countryCode: "US", limitType: "STEL", ppm: 300 },
    { authority: "ACGIH_TLV", countryCode: "US", limitType: "TWA", ppm: 200 },
    { authority: "ACGIH_TLV", countryCode: "US", limitType: "STEL", ppm: 300 },
    { authority: "NIOSH", countryCode: "US", limitType: "IDLH", ppm: 3000 },
  ], physical: { boilingPointC: 79.6, flashPointC: -9, ignitionTempC: 505, lelVolPct: 1.4, uelVolPct: 11.4, densityGCm3: 0.805 } },
  { name: "Methyl isobutyl ketone", casNumber: "108-10-1", formula: "C6H12O", unNumber: "1245", limits: [
    { authority: "OSHA_PEL", countryCode: "US", limitType: "TWA", ppm: 100, mgM3: 410 },
    { authority: "NIOSH_REL", countryCode: "US", limitType: "TWA", ppm: 50 },
    { authority: "ACGIH_TLV", countryCode: "US", limitType: "TWA", ppm: 20 },
    { authority: "ACGIH_TLV", countryCode: "US", limitType: "STEL", ppm: 75 },
    { authority: "NIOSH", countryCode: "US", limitType: "IDLH", ppm: 500 },
  ], physical: { boilingPointC: 117.9, flashPointC: 13, lelVolPct: 1.2, uelVolPct: 8 } },
  { name: "Methyl mercaptan", casNumber: "74-93-1", formula: "CH4S", unNumber: "1064", limits: [
    { authority: "OSHA_PEL", countryCode: "US", limitType: "Ceiling", ppm: 10, mgM3: 20 },
    { authority: "NIOSH_REL", countryCode: "US", limitType: "Ceiling", ppm: 0.5 },
    { authority: "ACGIH_TLV", countryCode: "US", limitType: "TWA", ppm: 0.5 },
    { authority: "NIOSH", countryCode: "US", limitType: "IDLH", ppm: 150 },
  ], physical: { boilingPointC: 5.9, flashPointC: -18, lelVolPct: 3.9, uelVolPct: 21.8 } },
  { name: "Nitric oxide", casNumber: "10102-43-9", formula: "NO", unNumber: "1660", limits: [
    { authority: "OSHA_PEL", countryCode: "US", limitType: "TWA", ppm: 25, mgM3: 30 },
    { authority: "NIOSH_REL", countryCode: "US", limitType: "TWA", ppm: 25 },
    { authority: "ACGIH_TLV", countryCode: "US", limitType: "TWA", ppm: 25 },
    { authority: "NIOSH", countryCode: "US", limitType: "IDLH", ppm: 100 },
  ], physical: { boilingPointC: -152 } },
  { name: "Nitrogen dioxide", casNumber: "10102-44-0", formula: "NO2", unNumber: "1067", limits: [
    { authority: "OSHA_PEL", countryCode: "US", limitType: "Ceiling", ppm: 5 },
    { authority: "NIOSH_REL", countryCode: "US", limitType: "STEL", ppm: 1 },
    { authority: "ACGIH_TLV", countryCode: "US", limitType: "TWA", ppm: 0.2 },
    { authority: "NIOSH", countryCode: "US", limitType: "IDLH", ppm: 20 },
  ], physical: { boilingPointC: 21.2 } },
  { name: "Ozone", casNumber: "10028-15-6", formula: "O3", limits: [
    { authority: "OSHA_PEL", countryCode: "US", limitType: "TWA", ppm: 0.1, mgM3: 0.2 },
    { authority: "NIOSH_REL", countryCode: "US", limitType: "Ceiling", ppm: 0.1 },
    { authority: "ACGIH_TLV", countryCode: "US", limitType: "TWA", ppm: 0.1 },
    { authority: "NIOSH", countryCode: "US", limitType: "IDLH", ppm: 5 },
  ], physical: { boilingPointC: -111.9 } },
  { name: "Pentane", casNumber: "109-66-0", formula: "C5H12", unNumber: "1265", limits: [
    { authority: "OSHA_PEL", countryCode: "US", limitType: "TWA", ppm: 1000 },
    { authority: "NIOSH_REL", countryCode: "US", limitType: "TWA", ppm: 120 },
    { authority: "ACGIH_TLV", countryCode: "US", limitType: "TWA", ppm: 1000 },
    { authority: "NIOSH", countryCode: "US", limitType: "IDLH", ppm: 1500 },
  ], physical: { boilingPointC: 36, flashPointC: -40, lelVolPct: 1.5, uelVolPct: 7.8 } },
  { name: "Phosgene", casNumber: "75-44-5", formula: "CCl2O", unNumber: "1076", limits: [
    { authority: "OSHA_PEL", countryCode: "US", limitType: "TWA", ppm: 0.1, mgM3: 0.4 },
    { authority: "NIOSH_REL", countryCode: "US", limitType: "TWA", ppm: 0.1 },
    { authority: "NIOSH_REL", countryCode: "US", limitType: "Ceiling", ppm: 0.2 },
    { authority: "ACGIH_TLV", countryCode: "US", limitType: "TWA", ppm: 0.1 },
    { authority: "NIOSH", countryCode: "US", limitType: "IDLH", ppm: 2 },
  ], physical: { boilingPointC: 8.2 } },
  { name: "Phosphine", casNumber: "7803-51-2", formula: "PH3", unNumber: "2199", limits: [
    { authority: "OSHA_PEL", countryCode: "US", limitType: "TWA", ppm: 0.3 },
    { authority: "NIOSH_REL", countryCode: "US", limitType: "TWA", ppm: 0.3 },
    { authority: "NIOSH_REL", countryCode: "US", limitType: "STEL", ppm: 1 },
    { authority: "ACGIH_TLV", countryCode: "US", limitType: "TWA", ppm: 0.3 },
    { authority: "NIOSH", countryCode: "US", limitType: "IDLH", ppm: 50 },
  ], physical: { boilingPointC: -87.7, ignitionTempC: 38 } },
  { name: "Propane", casNumber: "74-98-6", formula: "C3H8", unNumber: "1978", limits: [
    { authority: "OSHA_PEL", countryCode: "US", limitType: "TWA", ppm: 1000, mgM3: 1800 },
    { authority: "NIOSH_REL", countryCode: "US", limitType: "TWA", ppm: 1000 },
    { authority: "NIOSH", countryCode: "US", limitType: "IDLH", ppm: 2100 },
  ], physical: { boilingPointC: -42, flashPointC: -104, lelVolPct: 2.1, uelVolPct: 9.5 } },
  { name: "Propylene oxide", casNumber: "75-56-9", formula: "C3H6O", unNumber: "1280", limits: [
    { authority: "OSHA_PEL", countryCode: "US", limitType: "TWA", ppm: 100, mgM3: 240 },
    { authority: "NIOSH_REL", countryCode: "US", limitType: "TWA", ppm: 2 },
    { authority: "ACGIH_TLV", countryCode: "US", limitType: "TWA", ppm: 2 },
    { authority: "NIOSH", countryCode: "US", limitType: "IDLH", ppm: 400 },
  ], physical: { boilingPointC: 34, flashPointC: -37, lelVolPct: 2.3, uelVolPct: 36 } },
  { name: "Pyridine", casNumber: "110-86-1", formula: "C5H5N", unNumber: "1282", limits: [
    { authority: "OSHA_PEL", countryCode: "US", limitType: "TWA", ppm: 5, mgM3: 15 },
    { authority: "NIOSH_REL", countryCode: "US", limitType: "TWA", ppm: 5 },
    { authority: "ACGIH_TLV", countryCode: "US", limitType: "TWA", ppm: 1 },
    { authority: "NIOSH", countryCode: "US", limitType: "IDLH", ppm: 1000 },
  ], physical: { boilingPointC: 115, flashPointC: 20, ignitionTempC: 482, lelVolPct: 1.8, uelVolPct: 12.4 } },
  { name: "Silane", casNumber: "7803-62-5", formula: "SiH4", unNumber: "2203", limits: [
    { authority: "NIOSH_REL", countryCode: "US", limitType: "TWA", ppm: 5, mgM3: 7 },
    { authority: "ACGIH_TLV", countryCode: "US", limitType: "TWA", ppm: 5 },
  ], physical: { boilingPointC: -112 } },
  { name: "Styrene", casNumber: "100-42-5", formula: "C8H8", unNumber: "2055", limits: [
    { authority: "OSHA_PEL", countryCode: "US", limitType: "TWA", ppm: 100 },
    { authority: "OSHA_PEL", countryCode: "US", limitType: "Ceiling", ppm: 200 },
    { authority: "NIOSH_REL", countryCode: "US", limitType: "TWA", ppm: 50 },
    { authority: "NIOSH_REL", countryCode: "US", limitType: "STEL", ppm: 100 },
    { authority: "ACGIH_TLV", countryCode: "US", limitType: "TWA", ppm: 10 },
    { authority: "NIOSH", countryCode: "US", limitType: "IDLH", ppm: 700 },
  ], physical: { boilingPointC: 145, flashPointC: 31, lelVolPct: 0.9, uelVolPct: 6.8 } },
  { name: "Tetrachloroethylene", casNumber: "127-18-4", formula: "C2Cl4", unNumber: "1897", limits: [
    { authority: "OSHA_PEL", countryCode: "US", limitType: "TWA", ppm: 100 },
    { authority: "NIOSH_REL", countryCode: "US", limitType: "TWA", notes: "Ca" },
    { authority: "ACGIH_TLV", countryCode: "US", limitType: "TWA", ppm: 25 },
    { authority: "NIOSH", countryCode: "US", limitType: "IDLH", ppm: 150 },
  ], physical: { boilingPointC: 121 } },
  { name: "Tetrahydrofuran", casNumber: "109-99-9", formula: "C4H8O", unNumber: "2056", limits: [
    { authority: "OSHA_PEL", countryCode: "US", limitType: "TWA", ppm: 200, mgM3: 590 },
    { authority: "NIOSH_REL", countryCode: "US", limitType: "TWA", ppm: 200 },
    { authority: "ACGIH_TLV", countryCode: "US", limitType: "TWA", ppm: 50 },
    { authority: "NIOSH", countryCode: "US", limitType: "IDLH", ppm: 2000 },
  ], physical: { boilingPointC: 66, flashPointC: -14, ignitionTempC: 321, lelVolPct: 2, uelVolPct: 11.8, densityGCm3: 0.888 } },
  { name: "Trichloroethylene", casNumber: "79-01-6", formula: "C2HCl3", unNumber: "1710", limits: [
    { authority: "OSHA_PEL", countryCode: "US", limitType: "TWA", ppm: 100 },
    { authority: "OSHA_PEL", countryCode: "US", limitType: "Ceiling", ppm: 200 },
    { authority: "ACGIH_TLV", countryCode: "US", limitType: "TWA", ppm: 10 },
    { authority: "NIOSH", countryCode: "US", limitType: "IDLH", ppm: 1000 },
  ], physical: { boilingPointC: 87, densityGCm3: 1.46 } },
  { name: "Vinyl chloride", casNumber: "75-01-4", formula: "C2H3Cl", unNumber: "1086", limits: [
    { authority: "OSHA_PEL", countryCode: "US", limitType: "TWA", ppm: 1 },
    { authority: "OSHA_PEL", countryCode: "US", limitType: "Ceiling", ppm: 5 },
    { authority: "ACGIH_TLV", countryCode: "US", limitType: "TWA", ppm: 1 },
  ], physical: { boilingPointC: -13, flashPointC: -78, lelVolPct: 3.6, uelVolPct: 33 } },
  { name: "Aniline", casNumber: "62-53-3", formula: "C6H7N", unNumber: "1547", limits: [
    { authority: "OSHA_PEL", countryCode: "US", limitType: "TWA", ppm: 5, mgM3: 19 },
    { authority: "NIOSH_REL", countryCode: "US", limitType: "TWA", ppm: 2 },
    { authority: "ACGIH_TLV", countryCode: "US", limitType: "TWA", ppm: 2 },
    { authority: "NIOSH", countryCode: "US", limitType: "IDLH", ppm: 100 },
  ], physical: { boilingPointC: 184, flashPointC: 76, densityGCm3: 1.02 } },
  { name: "Nitrobenzene", casNumber: "98-95-3", formula: "C6H5NO2", unNumber: "1662", limits: [
    { authority: "OSHA_PEL", countryCode: "US", limitType: "TWA", ppm: 1, mgM3: 5 },
    { authority: "NIOSH_REL", countryCode: "US", limitType: "TWA", ppm: 1 },
    { authority: "ACGIH_TLV", countryCode: "US", limitType: "TWA", ppm: 1 },
    { authority: "NIOSH", countryCode: "US", limitType: "IDLH", ppm: 200 },
  ], physical: { boilingPointC: 211, flashPointC: 88, densityGCm3: 1.2 } },
  { name: "Naphthalene", casNumber: "91-20-3", formula: "C10H8", unNumber: "1334", limits: [
    { authority: "OSHA_PEL", countryCode: "US", limitType: "TWA", ppm: 10 },
    { authority: "ACGIH_TLV", countryCode: "US", limitType: "TWA", ppm: 10 },
    { authority: "NIOSH", countryCode: "US", limitType: "IDLH", ppm: 250 },
  ], physical: { boilingPointC: 218, meltingPointC: 80 } },
  { name: "Lead", casNumber: "7439-92-1", formula: "Pb", limits: [
    { authority: "OSHA_PEL", countryCode: "US", limitType: "TWA", mgM3: 0.05 },
    { authority: "NIOSH_REL", countryCode: "US", limitType: "TWA", mgM3: 0.05 },
    { authority: "ACGIH_TLV", countryCode: "US", limitType: "TWA", mgM3: 0.05 },
    { authority: "NIOSH", countryCode: "US", limitType: "IDLH", mgM3: 100 },
  ], physical: { boilingPointC: 1740, meltingPointC: 327, densityGCm3: 11.34 } },
  { name: "Tetraethyl lead", casNumber: "78-00-2", formula: "C8H20Pb", unNumber: "1649", limits: [
    { authority: "OSHA_PEL", countryCode: "US", limitType: "TWA", mgM3: 0.075 },
    { authority: "NIOSH_REL", countryCode: "US", limitType: "TWA", mgM3: 0.075 },
    { authority: "NIOSH", countryCode: "US", limitType: "IDLH", mgM3: 40 },
  ], physical: { boilingPointC: 200, flashPointC: 85 } },
  { name: "Dimethyl sulfate", casNumber: "77-78-1", formula: "C2H6O4S", unNumber: "1595", limits: [
    { authority: "OSHA_PEL", countryCode: "US", limitType: "TWA", ppm: 1, mgM3: 5 },
    { authority: "NIOSH_REL", countryCode: "US", limitType: "TWA", ppm: 0.1 },
    { authority: "ACGIH_TLV", countryCode: "US", limitType: "TWA", ppm: 0.1 },
    { authority: "NIOSH", countryCode: "US", limitType: "IDLH", ppm: 7 },
  ], physical: { boilingPointC: 188, flashPointC: 83 } },
  { name: "Ethyl acrylate", casNumber: "140-88-5", formula: "C5H8O2", unNumber: "1917", physical: { boilingPointC: 99, flashPointC: 10 } },
  { name: "Acetonitrile", casNumber: "75-05-8", formula: "C2H3N", unNumber: "1648", limits: [
    { authority: "OSHA_PEL", countryCode: "US", limitType: "TWA", ppm: 40, mgM3: 70 },
    { authority: "NIOSH_REL", countryCode: "US", limitType: "TWA", ppm: 20, mgM3: 34 },
    { authority: "ACGIH_TLV", countryCode: "US", limitType: "TWA", ppm: 20 },
    { authority: "NIOSH", countryCode: "US", limitType: "IDLH", ppm: 500 },
  ], physical: { boilingPointC: 81.6, flashPointC: 2, ignitionTempC: 524, lelVolPct: 4.4, uelVolPct: 16, densityGCm3: 0.786 } },
  { name: "Ethylene glycol", casNumber: "107-21-1", formula: "C2H6O2", limits: [
    { authority: "ACGIH_TLV", countryCode: "US", limitType: "Ceiling", mgM3: 100 },
  ], physical: { boilingPointC: 197.3, meltingPointC: -13, flashPointC: 111, densityGCm3: 1.113 } },
  { name: "Glycerol", casNumber: "56-81-5", formula: "C3H8O3", limits: [
    { authority: "OSHA_PEL", countryCode: "US", limitType: "TWA", mgM3: 10 },
  ], physical: { boilingPointC: 290, meltingPointC: 18, flashPointC: 160, densityGCm3: 1.261 } },
  { name: "Acetic anhydride", casNumber: "108-24-7", formula: "C4H6O3", unNumber: "1715", limits: [
    { authority: "OSHA_PEL", countryCode: "US", limitType: "TWA", ppm: 5, mgM3: 20 },
    { authority: "NIOSH_REL", countryCode: "US", limitType: "Ceiling", ppm: 5, mgM3: 20 },
    { authority: "ACGIH_TLV", countryCode: "US", limitType: "Ceiling", ppm: 5 },
    { authority: "NIOSH", countryCode: "US", limitType: "IDLH", ppm: 200 },
  ], physical: { boilingPointC: 139, flashPointC: 49, densityGCm3: 1.082 } },
  { name: "Ethyl benzene", casNumber: "100-41-4", formula: "C8H10", unNumber: "1175", limits: [
    { authority: "OSHA_PEL", countryCode: "US", limitType: "TWA", ppm: 100, mgM3: 435 },
    { authority: "NIOSH_REL", countryCode: "US", limitType: "TWA", ppm: 100 },
    { authority: "ACGIH_TLV", countryCode: "US", limitType: "TWA", ppm: 20 },
    { authority: "NIOSH", countryCode: "US", limitType: "IDLH", ppm: 800 },
  ], physical: { boilingPointC: 136, flashPointC: 15, lelVolPct: 0.8, uelVolPct: 6.7 } },
  { name: "Methyl methacrylate", casNumber: "80-62-6", formula: "C5H8O2", unNumber: "1247", limits: [
    { authority: "OSHA_PEL", countryCode: "US", limitType: "TWA", ppm: 100, mgM3: 410 },
    { authority: "NIOSH_REL", countryCode: "US", limitType: "TWA", ppm: 100 },
    { authority: "ACGIH_TLV", countryCode: "US", limitType: "TWA", ppm: 50 },
    { authority: "NIOSH", countryCode: "US", limitType: "IDLH", ppm: 1000 },
  ], physical: { boilingPointC: 101, flashPointC: 10, lelVolPct: 1.7, uelVolPct: 8.2 } },
  { name: "n-Butanol", casNumber: "71-36-3", formula: "C4H10O", unNumber: "1120", limits: [
    { authority: "OSHA_PEL", countryCode: "US", limitType: "TWA", ppm: 100, mgM3: 300 },
    { authority: "NIOSH_REL", countryCode: "US", limitType: "Ceiling", ppm: 50, mgM3: 150 },
    { authority: "ACGIH_TLV", countryCode: "US", limitType: "TWA", ppm: 20 },
    { authority: "NIOSH", countryCode: "US", limitType: "IDLH", ppm: 1400 },
  ], physical: { boilingPointC: 117, flashPointC: 37, lelVolPct: 1.4, uelVolPct: 11.2 } },
  { name: "Diethylamine", casNumber: "109-89-7", formula: "C4H11N", unNumber: "1154", limits: [
    { authority: "OSHA_PEL", countryCode: "US", limitType: "TWA", ppm: 25, mgM3: 75 },
    { authority: "NIOSH_REL", countryCode: "US", limitType: "TWA", ppm: 10, mgM3: 30 },
    { authority: "NIOSH_REL", countryCode: "US", limitType: "STEL", ppm: 25, mgM3: 75 },
    { authority: "ACGIH_TLV", countryCode: "US", limitType: "TWA", ppm: 5 },
    { authority: "NIOSH", countryCode: "US", limitType: "IDLH", ppm: 200 },
  ], physical: { boilingPointC: 55.5, flashPointC: -23, densityGCm3: 0.706 } },
  { name: "Triethylamine", casNumber: "121-44-8", formula: "C6H15N", unNumber: "1296", limits: [
    { authority: "OSHA_PEL", countryCode: "US", limitType: "TWA", ppm: 25, mgM3: 100 },
    { authority: "NIOSH_REL", countryCode: "US", limitType: "TWA", ppm: 10, mgM3: 40 },
    { authority: "NIOSH_REL", countryCode: "US", limitType: "STEL", ppm: 15, mgM3: 60 },
    { authority: "ACGIH_TLV", countryCode: "US", limitType: "TWA", ppm: 1 },
    { authority: "NIOSH", countryCode: "US", limitType: "IDLH", ppm: 200 },
  ], physical: { boilingPointC: 89, flashPointC: -11, densityGCm3: 0.726 } },
  { name: "Epichlorohydrin", casNumber: "106-89-8", formula: "C3H5ClO", unNumber: "2023", limits: [
    { authority: "OSHA_PEL", countryCode: "US", limitType: "TWA", ppm: 5 },
    { authority: "ACGIH_TLV", countryCode: "US", limitType: "TWA", ppm: 0.5 },
    { authority: "NIOSH", countryCode: "US", limitType: "IDLH", ppm: 75 },
  ], physical: { boilingPointC: 117, flashPointC: 31, densityGCm3: 1.18 } },
];
